Repository andela/cyclops-backend, pull requests merged in 2019-08, with the labels that each got.

#9 #167728010 Implementation for dotenv setup
  .env.sample
  README.md
  package.json
Labels: bn node/express backend, setup

#12 #167728006 Integrate Hound CI
  README.md
Labels: bn node/express backend, setup

#13 #167728006 Add Hound yml
  .hound.yml
Labels: bn node/express backend, setup

#8 #167728003 Setup postgresql db engine
  .env.example
  .hound.yml
  package-lock.json
  package.json
  src/config/config.js
  src/database/config.js
Labels: bn node/express backend, database

#16 #167957474 refactor database setup
  .env.example
  .env.sample
  .eslintrc.json
  package-lock.json
  package.json
  src/config/config.js
  src/database/config.js
Labels: bn node/express backend, setup

#17 #167728007 Setup Travis CI
  .eslintrc.json
  .hound.yml
  .travis.yml
  README.md
  package-lock.json
  package.json
  src/index.js
Labels: bn node/express backend, devops, setup

#19 #167728004 Complete sequelize setup using sequelize-cli
  .sequelizerc
  README.md
  package-lock.json
  package.json
  src/config/database.json
  src/database/migrations/20190816122841-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20190816125338-demo-user.js
Labels: bn node/express backend, database, setup

#15 #167728011 Setting up coveralls
  .coveralls.yml
  README.md
  package-lock.json
  package.json
Labels: bn node/express backend, code quality, devops, skill:setting up test coverage

#20 #167728008 Setup unit tests
  .coveralls.yml
  .sequelizerc
  .travis.yml
  package-lock.json
  package.json
  src/config/config.js
  src/config/database.json
  src/index.js
  tests/server.test.js
Labels: bn node/express backend

#22 #167728013 Setup Docker
  .dockerignore
  Dockerfile
Labels: bn node/express backend, setup

#21 #167728012 Setup API documentation with Swagger
  .sequelizerc
  package-lock.json
  package.json
  public/docs/swaggerDoc.json
  src/config/config.js
  src/controllers/UserController.js
  src/controllers/index.js
  src/index.js
  src/models/User.js
  src/models/index.js
  src/routes/index.js
  src/routes/user.js
  tests/server.test.js
  tests/user.test.js
Labels: bn node/express backend, documentation, setup
