Repository andela/cyclops-backend, pull requests merged in 2019-09, with the labels that each got.

#37 #167728017 Implementation of user signup feature
  .editorconfig
  .eslintrc.json
  package-lock.json
  package.json
  public/docs/swaggerDoc.json
  src/controllers/AuthController.js
  src/database/migrations/20190824180419-create-user.js
  src/middlewares/userAuth.js
  src/models/User.js
  src/modules/validator.js
  src/repositories/UserRepository.js
  src/routes/user.js
  src/services/socialOAuth.js
  tests/user.test.js
Labels: bn node/express backend

#36 #167728020 Password reset via email
  .circleci/config.yml
  .env.example
  .eslintrc.json
  .travis.yml
  package-lock.json
  package.json
  public/docs/swaggerDoc.json
  src/controllers/AuthController.js
  src/database/seeders/20190828110546-demo-user.js
  src/models/User.js
  src/modules/validator.js
  src/repositories/UserRepository.js
  src/routes/user.js
  src/utils/sendResponse.js
  tests/passwordReset.test.js
  tests/user.test.js
Labels: User auth, bn node/express backend

#39 #167728024 Implement user can make a return trip request
  .circleci/config.yml
  .travis.yml
  README.md
  package-lock.json
  package.json
  public/docs/swaggerDoc.json
  src/controllers/AuthController.js
  src/controllers/OfficeController.js
  src/controllers/TripRequestController.js
  src/database/migrations/20190827160544-create-user.js
  src/database/migrations/20190827160545-create-managers.js
  src/database/migrations/20190829082148-add-associations.js
  src/database/migrations/20190831150607-create-trip-request.js
  src/database/migrations/20190831150608-create-office-location.js
  src/database/migrations/20190831150622-create-trip-destination.js
  src/database/migrations/20190831150623-create-notifications.js
  src/database/seeders/20190825080303-create-users.js
  src/database/seeders/20190825080304-create-managers.js
  src/database/seeders/20190825080305-update-users.js
  src/database/seeders/20190828110546-demo-user.js
  src/database/seeders/20190829092036-create-office-locations.js
  src/middlewares/authenticateUser.js
  src/middlewares/requestValidation.js
  src/middlewares/userAuth.js
  src/models/Manager.js
  src/models/Notification.js
  src/models/User.js
  src/models/officelocation.js
  src/models/tripdestination.js
  src/models/triprequest.js
  src/modules/validator.js
  src/repositories/NotificationRepository.js
  src/repositories/OfficeLocationRepository.js
  src/repositories/TripDestinationRepository.js
  src/repositories/TripRequestRepository.js
  src/repositories/UserRepository.js
  src/routes/index.js
  src/routes/office.js
  src/routes/tripRequest.js
  src/utils/hashPassword.js
  src/utils/index.js
  tests/office.test.js
  tests/passwordReset.test.js
  tests/request.test.js
  tests/server.test.js
  tests/user.test.js
Labels: Travel Requests, bn node/express backend

#44 #167728022 Implementation of user profile edit
  .eslintrc.json
  package.json
  public/docs/swaggerDoc.json
  src/controllers/AuthController.js
  src/database/migrations/20190827160548-create-user.js
  src/middlewares/authenticateUser.js
  src/middlewares/index.js
  src/models/User.js
  src/repositories/UserRepository.js
  src/routes/index.js
  src/routes/user.js
  src/utils/sendResponse.js
  tests/index.js
  tests/mock.data.js
  tests/office.test.js
  tests/passwordReset.test.js
  tests/request.test.js
  tests/server.test.js
  tests/social.test.js
  tests/tokenProcessor.test.js
  tests/user.profile.edit.test.js
  tests/user.profile.view.test.js
  tests/user.signin.test.js
  tests/user.signout.test.js
  tests/user.signup.test.js
Labels: api, bn node/express backend

#41 #167728028 User role settings
  .eslintrc.json
  package-lock.json
  package.json
  src/controllers/AdminController.js
  src/controllers/AuthController.js
  src/database/migrations/20190827160548-create-user.js
  src/database/migrations/20190902190921-create-role.js
  src/database/migrations/20190902190941-create-permision.js
  src/database/migrations/20190902191142-create-role-permision.js
  src/database/seeders/20190825080303-create-users.js
  src/database/seeders/20190902194109-roles.js
  src/database/seeders/20190902194959-permissions.js
  src/middlewares/verifyRoles.js
  src/models/User.js
  src/models/permision.js
  src/models/role.js
  src/models/rolepermision.js
  src/repositories/UserRepository.js
  src/routes/office.js
  src/routes/user.js
  tests/index.js
  tests/office.test.js
  tests/passwordReset.test.js
  tests/user.signup.test.js
  tests/userRole.test.js
Labels: bn node/express backend, roles and permissions settings

#49 #168365057 Implementation of a reusable in-App notification module
  package.json
  public/docs/swaggerDoc.json
  src/app.js
  src/controllers/AdminController.js
  src/controllers/AuthController.js
  src/controllers/ExampleUserNotificationController.js
  src/middlewares/authenticateUser.js
  src/middlewares/userAuth.js
  src/repositories/NotificationRepository.js
  src/routes/index.js
  src/routes/notifications.js
  src/routes/user.js
  src/utils/NotificationHelpers.js
  src/utils/getUserInfo.js
  tests/index.js
  tests/mock.data.js
  tests/request.test.js
  tests/server.test.js
  tests/social.login.test.js
  tests/user.info.getter.js
  tests/user.profile.edit.test.js
  tests/userRole.test.js
  tests/util.notification.test.js
Labels: bn node/express backend

#48 #167728034 Complete endpoint for user can delete comment posted within comment thread
  .eslintrc.json
  .sequelizerc
  package-lock.json
  public/docs/swaggerDoc.json
  src/controllers/AdminController.js
  src/controllers/AuthController.js
  src/controllers/CommentController.js
  src/controllers/TripRequestController.js
  src/database/migrations/20190903210241-create-comment.js
  src/database/seeders/20190829092037-create-trip-request.js
  src/database/seeders/20190831152452-create-trip-request.js
  src/database/seeders/20190907183906-create-comments.js
  src/middlewares/requestValidation.js
  src/middlewares/verifyRoles.js
  src/models/Comment.js
  src/models/TripRequest.js
  src/repositories/CommentRepository.js
  src/repositories/TripRequestRepository.js
  src/routes/comment.js
  src/utils/createAccessToken.js
  tests/comment.test.js
  tests/index.js
  tests/passwordReset.test.js
  tests/user.info.getter.js
  tests/util.notification.test.js
Labels: Travel Requests, bn node/express backend

#47 #168244900 Implements user can edit comment on a trip request
  public/docs/swaggerDoc.json
  src/controllers/CommentController.js
  src/controllers/TripRequestController.js
  tests/passwordReset.test.js
Labels: Travel Requests, bn node/express backend
